name: Builds
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-and-run:
    name: Build & run

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Compile Updater
        run: iscc /DAppName=Updater /DAppVersion=1.0 src\pl2303.iss
        shell: cmd

      - name: Run Updater
        run: builds\output\Updater.exe /VERYSILENT /SUPPRESSMSGBOXES /CI=true /LOG=C:\updater.txt
        shell: cmd

      - name: Compile Setup
        run: iscc /DAppName=Updater /DAppVersion=1.0 src\setup\setup.iss
        shell: cmd

      - name: Run Setup
        run: builds\output\UpdaterSetup.exe /VERYSILENT /SUPPRESSMSGBOXES /LOG=C:\setup.txt
        shell: cmd

      - name : Upload logs
        uses: actions/upload-artifact@v3
        with:
          path: |
            C:\updater.txt
            C:\setup.txt
